_wandb:
    value:
        cli_version: 0.28.1
        e:
            lu1pidricwavr0yidhj88ckt8k5y4h4m:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    macModel: MacBookAir10,1
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "19327352832"
                args:
                    - config=configs/sweeps/fcp_lbf_stage1/learning_rate=0.001_entropy_coef=0.01_total_timesteps=1000000.0.json
                codePath: .venv/bin/oaht-bench
                codePathLocal: .venv/bin/oaht-bench
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "747169746944"
                email: conorw8@gmail.com
                executable: /Users/conorwallace/Documents/Personal/Projects/OAHT-Bench/.venv/bin/python3
                git:
                    commit: b4359cfc56f951c37120e397b39184cce3a04b4f
                    remote: https://github.com/conor-wallace/OAHT-Bench.git
                host: Conors-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit
                program: /Users/conorwallace/Documents/Personal/Projects/OAHT-Bench/.venv/bin/oaht-bench
                python: CPython 3.11.14
                root: /Users/conorwallace/Documents/Personal/Projects/OAHT-Bench
                startedAt: "2026-08-05T13:57:51.506940Z"
                writerId: lu1pidricwavr0yidhj88ckt8k5y4h4m
        m:
            - "1": train_step
              "6":
                - 3
              "7": []
            - "1": checkpoint
              "6":
                - 3
              "7": []
            - "2": Returns/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": Train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": Losses/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": Eval/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 12
                - 45
                - 49
            "2":
                - 12
                - 45
                - 49
            "3":
                - 2
                - 7
                - 16
            "4": 3.11.14
            "5": 0.28.1
            "10":
                - 20
            "12": 0.28.1
            "13": darwin-arm64
ENV_KWARGS:
    value:
        different_levels: true
        grid_size: 12
        num_agents: 2
        num_food: 6
ENV_NAME:
    value: lbf
ROLLOUT_LENGTH:
    value: 128
TASK_NAME:
    value: lbf_12x12
algorithm:
    value:
        ACTIVATION: tanh
        ACTOR_TYPE: mlp
        ALG: fcp
        ANNEAL_LR: false
        CLIP_EPS: 0.03
        ENT_COEF: 0.01
        ENV_KWARGS:
            different_levels: true
            grid_size: 12
            num_agents: 2
            num_food: 6
        ENV_NAME: lbf
        FC_HIDDEN_DIM: 64
        GAE_LAMBDA: 0.95
        GAMMA: 0.99
        LR: 0.001
        MAX_GRAD_NORM: 1
        NUM_CHECKPOINTS: 5
        NUM_ENVS: 8
        NUM_EVAL_EPISODES: 20
        NUM_MINIBATCHES: 4
        NUM_SEEDS: 1
        PARTNER_POP_SIZE: 5
        ROLLOUT_LENGTH: 128
        TOTAL_TIMESTEPS: 1e+06
        TRAIN_SEED: 20374
        UPDATE_EPOCHS: 15
        VF_COEF: 0.5
label:
    value: fcp_lbf_stage1__learning_rate=0.001_entropy_coef=0.01_total_timesteps=1000000.0
local_logger:
    value:
        save_eval_out: true
        save_train_out: true
logger:
    value:
        log_eval_out: true
        log_train_out: true
        verbose: false
name:
    value: lbf_12x12/fcp/fcp_lbf_stage1__learning_rate=0.001_entropy_coef=0.01_total_timesteps=1000000.0
run_dir:
    value: results/teammate_generation/fcp_lbf_stage1__learning_rate=0.001_entropy_coef=0.01_total_timesteps=1000000.0-d0ce4e4df510
run_heldout_eval:
    value: false
task:
    value:
        ENV_KWARGS:
            different_levels: true
            grid_size: 12
            num_agents: 2
            num_food: 6
        ENV_NAME: lbf
        ROLLOUT_LENGTH: 128
        TASK_NAME: lbf_12x12
train_ego:
    value: false
