defaults:
  - ippo/_base_
  - _self_

TOTAL_TIMESTEPS: 1e8
SEED: 1234567
LR: .0005
NUM_ENVS: 128
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
CLIP_EPS: 0.2
ENT_COEF: 0.01
ANNEAL_LR: False
MAX_GRAD_NORM: 0.5
ACTOR_TYPE: s5
S5_D_MODEL: 128
S5_SSM_SIZE: 128
S5_BLOCKS: 1
S5_ACTOR_CRITIC_HIDDEN_DIM: 1024
ACTIVATION: 'relu'
